# Generated by Django 5.2.8 on 2025-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(choices=[('A', 'Usuário A'), ('B', 'Usuário B')], help_text='Identifica se a mensagem é do Usuário A ou B', max_length=1)),
                ('conteudo', models.TextField(help_text='Conteúdo da mensagem enviada pelo usuário')),
                ('resposta', models.TextField(help_text='Resposta automática gerada pelo sistema')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação da mensagem')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-timestamp'],
            },
        ),
    ]
